import Head from "next/head";
import { Apresentacao } from "../components/Apresentacao";
import { Header } from "../components/Header";
import { Solucoes } from "../components/Solucoes";
export default function Home() {
  return (
    <div className="bg-[#1c1c1c] w-full h-full">
      <Head>
        <title>Igneo Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#1c1c1c]  px-2">
        <Header/>
        <Apresentacao />
        <Solucoes />
      </main>

      
    </div>
  );
}
